In [123]:
import pandas as pd
import numpy as np

In [124]:
###Import data
##1. Find file in finder
##2. Option + Command + C
##3. Paste Info read_csv(r” ”)

df = pd.ExcelFile(r"/Users/holly/Desktop/nycdoe/10202020 SY2021 YTD MASTER THRIVE Data File HB v3.xlsx")

In [125]:
#Read data from corrrect tab.
#schools = suspmaster.parse('schools')
data = df.parse('THRIVE MASTER')
src_schools = df.parse('SRC Schools')

In [126]:
data

,Quarter,Response ID,Time Started,Date Submitted,MONTH,Date Submitted - Simple Date,Days Between Date Submitted and Date Provided,Username:New Login/Password,Password:New Login/Password,"Did you provide support at a school, central office (deployment for staff support ONLY) or REC?",...,What type of support did you provide that was not a direct student support? Did you attempt to contact a student without response?,Student OSIS number of student (attempt to contact student):,Did you provide support to staff and/or family in response to a crisis incident or to provide preventive (ongoing) supports?,What type of staff/family preventive (ongoing) support did you provide?,How many unique school staff members participated in this training?,What type of staff/family crisis response support did you provide?,Student OSIS number of student discussed in case consultation with staff and/or family:,Did you refer this student(s) to external mental health supports?,Which external health support did you refer this student to?,CASE NOTES
0,Q1,475,"Sep 25, 2020 12:04:02 pm","Sep 25, 2020 1:14:06 pm",SEPTEMBER,9/25/2020,0,npeterscamille@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC engaged students in a remote conversation ...
1,Q1,326,"Sep 23, 2020 11:53:35 am","Sep 23, 2020 11:57:32 am",SEPTEMBER,9/23/2020,1,npeterscamille@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC engaged students in a remote conversation ...
2,Q1,466,"Sep 25, 2020 11:35:01 am","Sep 25, 2020 11:37:37 am",SEPTEMBER,9/25/2020,1,npeterscamille@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC engaged in a workshop using the bridge to ...
3,Q1,467,"Sep 25, 2020 11:38:22 am","Sep 25, 2020 11:40:24 am",SEPTEMBER,9/25/2020,1,npeterscamille@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC engaged in a workshop using the bridge to ...
4,Q1,1060,"Oct 2, 2020 1:13:40 pm","Oct 2, 2020 1:19:57 pm",SEPTEMBER,10/2/2020,3,JRubioperalta@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Social worker co-facilitated circle group for ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8841,Q2,13822,"Dec 18, 2020 5:05:55 pm","Dec 18, 2020 5:10:27 pm",December,2020-12-18 00:00:00,0,cknights@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,CBO,SRC engaged in check-in with student via phone...
8842,Q2,14569,"Dec 23, 2020 4:14:20 pm","Dec 23, 2020 4:28:03 pm",December,2020-12-23 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Student referred by GC for incident she shared...
8843,Q2,12126,"Dec 11, 2020 7:53:33 pm","Dec 11, 2020 8:00:50 pm",December,2020-12-11 00:00:00,1,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Student referred by GC for support around her ...
8844,Q2,13858,"Dec 18, 2020 6:10:55 pm","Dec 18, 2020 6:22:48 pm",December,2020-12-18 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Student supported around the challenges she re...
8845,Q2,14590,"Dec 23, 2020 5:36:26 pm","Dec 23, 2020 5:47:26 pm",December,2020-12-23 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Student shared that she was a different person...

In [127]:
#Rename DIRECT SUPPORT STUDENT OSIS NUMBER to student_id
#Source: https://stackoverflow.com/questions/11346283/renaming-columns-in-pandas
data = data.rename(columns={'DIRECT SUPPORT STUDENT OSIS NUMBER': 'student_id', 'Did you provide direct student support in response to a crisis incident or to provide preventive (ongoing) support?': 'service_type', 'Did you refer this student(s) to external mental health supports? ': 'external_referral', 'Did you provide 1:1 (individual) support or 1:2+ (group) student support?': 'individual_group'})

In [128]:
#Create a new column with DBN only from DBN:DBN - Cascading Dropdown
data['DBN'] = data['DBN:DBN - Cascading Dropdown'].apply(lambda x: x[0:6])

In [129]:
data

,Quarter,Response ID,Time Started,Date Submitted,MONTH,Date Submitted - Simple Date,Days Between Date Submitted and Date Provided,Username:New Login/Password,Password:New Login/Password,"Did you provide support at a school, central office (deployment for staff support ONLY) or REC?",...,Student OSIS number of student (attempt to contact student):,Did you provide support to staff and/or family in response to a crisis incident or to provide preventive (ongoing) supports?,What type of staff/family preventive (ongoing) support did you provide?,How many unique school staff members participated in this training?,What type of staff/family crisis response support did you provide?,Student OSIS number of student discussed in case consultation with staff and/or family:,external_referral,Which external health support did you refer this student to?,CASE NOTES,DBN
0,Q1,475,"Sep 25, 2020 12:04:02 pm","Sep 25, 2020 1:14:06 pm",SEPTEMBER,9/25/2020,0,npeterscamille@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC engaged students in a remote conversation ...,19K364
1,Q1,326,"Sep 23, 2020 11:53:35 am","Sep 23, 2020 11:57:32 am",SEPTEMBER,9/23/2020,1,npeterscamille@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC engaged students in a remote conversation ...,19K364
2,Q1,466,"Sep 25, 2020 11:35:01 am","Sep 25, 2020 11:37:37 am",SEPTEMBER,9/25/2020,1,npeterscamille@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC engaged in a workshop using the bridge to ...,19K660
3,Q1,467,"Sep 25, 2020 11:38:22 am","Sep 25, 2020 11:40:24 am",SEPTEMBER,9/25/2020,1,npeterscamille@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC engaged in a workshop using the bridge to ...,19K660
4,Q1,1060,"Oct 2, 2020 1:13:40 pm","Oct 2, 2020 1:19:57 pm",SEPTEMBER,10/2/2020,3,JRubioperalta@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Social worker co-facilitated circle group for ...,28Q686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8841,Q2,13822,"Dec 18, 2020 5:05:55 pm","Dec 18, 2020 5:10:27 pm",December,2020-12-18 00:00:00,0,cknights@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,CBO,SRC engaged in check-in with student via phone...,15K463
8842,Q2,14569,"Dec 23, 2020 4:14:20 pm","Dec 23, 2020 4:28:03 pm",December,2020-12-23 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Student referred by GC for incident she shared...,27Q226
8843,Q2,12126,"Dec 11, 2020 7:53:33 pm","Dec 11, 2020 8:00:50 pm",December,2020-12-11 00:00:00,1,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Student referred by GC for support around her ...,27Q226
8844,Q2,13858,"Dec 18, 2020 6:10:55 pm","Dec 18, 2020 6:22:48 pm",December,2020-12-18 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Student supported around the challenges she re...,27Q226
8845,Q2,14590,"Dec 23, 2020 5:36:26 pm","Dec 23, 2020 5:47:26 pm",December,2020-12-23 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Student shared that she was a different person...,27Q226

In [130]:
#Source: https://cmdlinetips.com/2018/03/how-to-filter-a-pandas-dataframe-based-on-null-values-of-a-column/
#Remove records with missing student_ids
#176 is confirmed

data2 = data[data.student_id.notnull()].DBN.nunique()
data2

197

In [131]:
#data.groupby('service_type').student_id.nunique()
students_served = data.groupby('DBN').student_id.nunique()
students_served

DBN
01M332      3
01M378      4
01M450     45
02M135     64
02M139      6
         ...
32K545      6
32K552      3
32K554      3
32K556    101
32K562     25
Name: student_id, Length: 197, dtype: int64

In [132]:
#schools_susptype = schools.merge(susptypefinal, left_on='DBN', right_on='ATS', how='left')
school_services = src_schools.merge(students_served, left_on='DBN', right_on='DBN', how='left')

In [133]:
school_services

,DBN,Borough,Cluster #,Building Code,Building Name,School Name,Address,Principal Name,student_id
0,15K429,K,K01,K293,J.H.S. 293 - BROOKLYN,Digital Arts and Cinema Technology High School,284 BALTIC STREET,Dawn Meconi,4.0
1,13K483,K,K01,K313,ADAMS STREET EDUCATIONAL CAMPUS - K,The Urban Assembly School for Law and Justice,283 ADAMS STREET,MERILEE VALENTINO,1.0
2,13K527,K,K01,K313,ADAMS STREET EDUCATIONAL CAMPUS - K,Urban Assembly Institute of Math and Science f...,283 ADAMS STREET,Kiri Soares,11.0
3,13K674,K,K01,K580,GEORGE WESTINGHOUSE VOC HS - K,"City Polytechnic High School of Engineering, A...",105 TECH PLACE,April Mckoy,6.0
4,13K313,K,K01,K611,DOCK ST CAMPUS - BROOKLYN,Dock Street School for STEAM Studies,19 DOCK STREET,Melissa Vaughan,4.0
...,...,...,...,...,...,...,...,...,...
289,10X353,X,X07,X440,DEWITT CLINTON HS - X,World View High School,100 WEST MOSHOLU PARKWAY SOUTH,Martin Hernandez,NaN
290,10X440,X,X07,X440,DEWITT CLINTON HS - X,DeWitt Clinton High School,100 WEST MOSHOLU PARKWAY SOUTH,Pierre Orbe,11.0
291,10X445,X,X07,X445,BRONX HS OF SCIENCE - X,The Bronx High School of Science,75 WEST 205 STREET,Jean Donahue,17.0
292,10X696,X,X07,X905,HS OF AMERICAN STUDIES - BRONX,High School of American Studies at Lehman College,2925 GOULDEN AVENUE,ALESSANDRO WEISS,2.0
293,13K499,Closed 7/1/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [134]:
school_services.drop('Borough', axis = 1, inplace = True)
school_services.drop('Cluster #', axis = 1, inplace = True)
school_services.drop('Building Code', axis = 1, inplace = True)
school_services.drop('Building Name', axis = 1, inplace = True)
school_services.drop('Address', axis = 1, inplace = True)

In [135]:
school_services

,DBN,School Name,Principal Name,student_id
0,15K429,Digital Arts and Cinema Technology High School,Dawn Meconi,4.0
1,13K483,The Urban Assembly School for Law and Justice,MERILEE VALENTINO,1.0
2,13K527,Urban Assembly Institute of Math and Science f...,Kiri Soares,11.0
3,13K674,"City Polytechnic High School of Engineering, A...",April Mckoy,6.0
4,13K313,Dock Street School for STEAM Studies,Melissa Vaughan,4.0
...,...,...,...,...
289,10X353,World View High School,Martin Hernandez,NaN
290,10X440,DeWitt Clinton High School,Pierre Orbe,11.0
291,10X445,The Bronx High School of Science,Jean Donahue,17.0
292,10X696,High School of American Studies at Lehman College,ALESSANDRO WEISS,2.0
293,13K499,NaN,NaN,NaN

In [136]:
#Export data to excel: https://datatofish.com/export-dataframe-to-excel/
#df.to_excel(r'Path to store the exported excel file\File Name.xlsx', sheet_name='Your sheet name', index = False)
#Formatting: https://xlsxwriter.readthedocs.io/working_with_pandas.html

school_services.to_excel(r"/Users/holly/Desktop/nycdoe/01152021 Students Served by School.xlsx", sheet_name='Student Services',header=True, merge_cells=False, index=False)

In [64]:
#YTD: Unique number of schools served -- NOT WORKING
#data2.DBN.nunique()

#3-YTD: Number of unique students who participated in a service delivered by an SRC either in response to a crisis incident or to provide preventative service.

In [65]:
#data2.student_id.nunique()

data2 = data[data.student_id.notnull()].student_id.nunique()
data2

3693

#3a-YTD: Number of unique students who participated in a service delivered by an SRC in response to a crisis incident
#3b-YTD: Number of unique students who participated in a service delivered by an SRC in response to a preventative incident

In [66]:

data.groupby('service_type').student_id.nunique()

#data3 = data[data.student_id.notnull()].groupby('service_type').student_id.nunique()
#data3

service_type
Crisis                    74
Preventive (Ongoing)    3669
Name: student_id, dtype: int64

YTD: Total number of services provided by crisis/preventative:

In [67]:
data.groupby('service_type').student_id.count()

service_type
Crisis                    83
Preventive (Ongoing)    8763
Name: student_id, dtype: int64

#4-YTD: Percentage of students who participated in a service delivered by an SRC AND who have been referred to external mental health services?

In [68]:
#Unique students served and referred to external mental health service

referred = data.query('external_referral == "Yes"').student_id.nunique()
referred

113

In [69]:
pcnt_referred = referred / data.student_id.nunique()
pcnt_referred

0.030598429461142704

In [70]:
#YTD: Total number of services grouped by external_referral
data.groupby('external_referral').student_id.count()

external_referral
No     8657
Yes     189
Name: student_id, dtype: int64

In [71]:
# YTD: Unique students served grouped by external_referral
data.groupby('external_referral').student_id.nunique()

external_referral
No     3650
Yes     113
Name: student_id, dtype: int64

#4a-YTD: Among students who have participated in a mental health session delivered by an SRC in response to a crisis incident, the percentage of students who had been referred to external mental health services.

In [72]:
#4a-YTD: Among students who have participated in a mental health session delivered by an SRC in response to a crisis incident, the percentage of students who had been referred to external mental health services.

crisis_referred = data.query('external_referral == "Yes" & service_type == "Crisis"').student_id.nunique()
crisis_referred

14

In [73]:
data.query('service_type == "Crisis"').student_id.nunique()

74

In [74]:
pcnt_crisis_referred = crisis_referred / data.query('service_type == "Crisis"').student_id.nunique()
pcnt_crisis_referred

0.1891891891891892

#4b-YTD: Among students who have participated in a mental health session delivered by an SRC in response to a preventative service, the percentage of students who had been referred to external mental health services.

In [75]:
#4b-YTD: Among students who have participated in a mental health session delivered by an SRC in response to a preventative service, the percentage of students who had been referred to external mental health services.

prevent_referred = data.query('external_referral == "Yes" & service_type == "Preventive (Ongoing)"').student_id.nunique()
prevent_referred

106

In [76]:
data.query('service_type == "Preventive (Ongoing)"').student_id.nunique()

3669

In [77]:
pcnt_prevent_referred = prevent_referred / data.query('service_type == "Preventive (Ongoing)"').student_id.nunique()
pcnt_prevent_referred

0.028890705914418096

#5-YTD: The number of unique schools that received support from an SRC in response to a crisis or to provide a preventative service.

In [79]:
##data2.DBN.nunique()
data2 = data[data.student_id.notnull()].DBN.nunique()
data2

197

#5a-YTD: The number of unique schools that received support from an SRC in response to a crisis incident.

In [80]:
#5a-YTD: The number of unique schools that received support from an SRC in response to a crisis incident.
data.query('service_type == "Crisis"').DBN.nunique()

43

#5b-YTD: The number of unique schools that received support from an SRC in response to a preventative service.

In [81]:
#5b-YTD: The number of unique schools that received support from an SRC in response to a preventative service.
data.query('service_type == "Preventive (Ongoing)"').DBN.nunique()

196

In [82]:
#Unique students served by service format: 'individual_group'

data.groupby('individual_group').student_id.nunique()
#data[data.student_id.notnull()].student_id.nunique('individual_group')

individual_group
1:1 (individual)    1122
1:2+ (group)        2697
Name: student_id, dtype: int64

In [83]:
#Number of services provided by service format: 'individual_group'
data.groupby('individual_group').student_id.count()

individual_group
1:1 (individual)    3233
1:2+ (group)        5613
Name: student_id, dtype: int64

#6-YTD: Number of unique students who have participated in an individual (1:1) mental health session delivered by an SRC in response to a crisis incident. ['individual_group']

In [84]:
#6-YTD: Number of unique students who have participated in an individual (1:1) mental health session delivered by an SRC in response to a crisis incident. ['individual_group']
crisis_individual = data.query('individual_group == "1:1 (individual)" & service_type == "Crisis"').student_id.nunique()
crisis_individual

64

#7-YTD: Number of uniques students who have participated in an individual (1:2+) mental health session delivered by an SRC in response to a crisis incident.

In [85]:
#7-YTD: Number of uniques students who have participated in an individual (1:2+) mental health session delivered by an SRC in response to a crisis incident.
crisis_group = data.query('individual_group == "1:2+ (group)" & service_type == "Crisis"').student_id.nunique()
crisis_group

10

#8-YTD: Number of uniques students who have participated in an individual (1:1) mental health session delivered by an SRC in response to a preventative.

In [86]:
#8-YTD: Number of uniques students who have participated in an individual (1:1) mental health session delivered by an SRC in response to a preventative.
prevent_individual = data.query('individual_group == "1:1 (individual)" & service_type == "Preventive (Ongoing)"').student_id.nunique()
prevent_individual

1108

#9-YTD: Number of uniques students who have participated in an individual (1:2+) mental health session delivered by an SRC in response to a preventative.

In [87]:
#9-YTD: Number of uniques students who have participated in an individual (1:2+) mental health session delivered by an SRC in response to a preventative.
prevent_group = data.query('individual_group == "1:2+ (group)" & service_type == "Preventive (Ongoing)"').student_id.nunique()
prevent_group

2687

##QUARTER 2 DATA METRICS

In [88]:
q2 = data.query('Quarter == "Q2"')

In [89]:
q2

,Quarter,Response ID,Time Started,Date Submitted,MONTH,Date Submitted - Simple Date,Days Between Date Submitted and Date Provided,Username:New Login/Password,Password:New Login/Password,"Did you provide support at a school, central office (deployment for staff support ONLY) or REC?",...,Student OSIS number of student (attempt to contact student):,Did you provide support to staff and/or family in response to a crisis incident or to provide preventive (ongoing) supports?,What type of staff/family preventive (ongoing) support did you provide?,How many unique school staff members participated in this training?,What type of staff/family crisis response support did you provide?,Student OSIS number of student discussed in case consultation with staff and/or family:,external_referral,Which external health support did you refer this student to?,CASE NOTES,DBN
356,Q2,3958,"Oct 26, 2020 1:07:38 pm","Oct 26, 2020 1:09:39 pm",OCTOBER,10/26/2020,3,lhowell4@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,In honor of National Bullying Prevention Month...,24Q455
357,Q2,3810,"Oct 26, 2020 9:18:36 am","Oct 26, 2020 9:20:00 am",OCTOBER,10/26/2020,3,Jmilitello3@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC facilitated bullying prevention workshop f...,24Q455
358,Q2,5514,"Oct 30, 2020 4:42:59 pm","Oct 30, 2020 4:51:45 pm",OCTOBER,10/30/2020,3,kpeters9@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SCR Co-facilitated red ribbon week activities ...,19K510
359,Q2,4890,"Oct 29, 2020 1:58:51 pm","Oct 29, 2020 2:01:08 pm",OCTOBER,10/29/2020,1,lhowell4@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC facilitated a student presentation which f...,24Q455
360,Q2,4700,"Oct 29, 2020 10:30:35 am","Oct 29, 2020 10:31:51 am",OCTOBER,10/29/2020,1,jmilitello3@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC facilitated sexual harassment workshop for...,24Q455
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8841,Q2,13822,"Dec 18, 2020 5:05:55 pm","Dec 18, 2020 5:10:27 pm",December,2020-12-18 00:00:00,0,cknights@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,Yes,CBO,SRC engaged in check-in with student via phone...,15K463
8842,Q2,14569,"Dec 23, 2020 4:14:20 pm","Dec 23, 2020 4:28:03 pm",December,2020-12-23 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Student referred by GC for incident she shared...,27Q226
8843,Q2,12126,"Dec 11, 2020 7:53:33 pm","Dec 11, 2020 8:00:50 pm",December,2020-12-11 00:00:00,1,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Student referred by GC for support around her ...,27Q226
8844,Q2,13858,"Dec 18, 2020 6:10:55 pm","Dec 18, 2020 6:22:48 pm",December,2020-12-18 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Student supported around the challenges she re...,27Q226
8845,Q2,14590,"Dec 23, 2020 5:36:26 pm","Dec 23, 2020 5:47:26 pm",December,2020-12-23 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Student shared that she was a different person...,27Q226

In [90]:
q2.head()

,Quarter,Response ID,Time Started,Date Submitted,MONTH,Date Submitted - Simple Date,Days Between Date Submitted and Date Provided,Username:New Login/Password,Password:New Login/Password,"Did you provide support at a school, central office (deployment for staff support ONLY) or REC?",...,Student OSIS number of student (attempt to contact student):,Did you provide support to staff and/or family in response to a crisis incident or to provide preventive (ongoing) supports?,What type of staff/family preventive (ongoing) support did you provide?,How many unique school staff members participated in this training?,What type of staff/family crisis response support did you provide?,Student OSIS number of student discussed in case consultation with staff and/or family:,external_referral,Which external health support did you refer this student to?,CASE NOTES,DBN
356,Q2,3958,"Oct 26, 2020 1:07:38 pm","Oct 26, 2020 1:09:39 pm",OCTOBER,10/26/2020,3,lhowell4@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,In honor of National Bullying Prevention Month...,24Q455
357,Q2,3810,"Oct 26, 2020 9:18:36 am","Oct 26, 2020 9:20:00 am",OCTOBER,10/26/2020,3,Jmilitello3@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC facilitated bullying prevention workshop f...,24Q455
358,Q2,5514,"Oct 30, 2020 4:42:59 pm","Oct 30, 2020 4:51:45 pm",OCTOBER,10/30/2020,3,kpeters9@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SCR Co-facilitated red ribbon week activities ...,19K510
359,Q2,4890,"Oct 29, 2020 1:58:51 pm","Oct 29, 2020 2:01:08 pm",OCTOBER,10/29/2020,1,lhowell4@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC facilitated a student presentation which f...,24Q455
360,Q2,4700,"Oct 29, 2020 10:30:35 am","Oct 29, 2020 10:31:51 am",OCTOBER,10/29/2020,1,jmilitello3@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,SRC facilitated sexual harassment workshop for...,24Q455

In [91]:
#NOT CORRECT??
#Q2: Unique number of schools served
q2.DBN.nunique()

196

#3-Q2: Number of unique students who participated in a service delivered by an SRC either in response to a crisis incident or to provide preventative service.

In [92]:
#Confirmed - this is correct
q2.student_id.nunique()

3591

#3a-Q2: Number of unique students who participated in a service delivered by an SRC in response to a crisis incident
#3b-Q2: Number of unique students who participated in a service delivered by an SRC in response to a preventative incident

In [93]:

q2.groupby('service_type').student_id.nunique()

service_type
Crisis                    67
Preventive (Ongoing)    3569
Name: student_id, dtype: int64

Q2: Total number of services provided by crisis/preventative:

In [94]:
q2.groupby('service_type').student_id.count()

service_type
Crisis                    75
Preventive (Ongoing)    8415
Name: student_id, dtype: int64

#4-Q2: Percentage of students who participated in a service delivered by an SRC AND who have been referred to external mental health services?

In [95]:

#Unique students served and referred to external mental health service
referred = q2.query('external_referral == "Yes"').student_id.nunique()
referred

111

In [96]:
pcnt_referred = referred / q2.student_id.nunique()
pcnt_referred

0.030910609857978277

In [97]:
#Q2: Total number of services grouped by external_referral
q2.groupby('external_referral').student_id.count()

external_referral
No     8304
Yes     186
Name: student_id, dtype: int64

In [98]:
# Q2: Unique students served grouped by external_referral
q2.groupby('external_referral').student_id.nunique()

external_referral
No     3548
Yes     111
Name: student_id, dtype: int64

#4a-Q2: Among students who have participated in a mental health session delivered by an SRC in response to a crisis incident, the percentage of students who had been referred to external mental health services.

In [99]:

crisis_referred = q2.query('external_referral == "Yes" & service_type == "Crisis"').student_id.nunique()
crisis_referred

14

In [100]:
q2.query('service_type == "Crisis"').student_id.nunique()

67

In [101]:
pcnt_crisis_referred = crisis_referred / q2.query('service_type == "Crisis"').student_id.nunique()
pcnt_crisis_referred

0.208955223880597

#4b-Q2: Among students who have participated in a mental health session delivered by an SRC in response to a preventative service, the percentage of students who had been referred to external mental health services.

In [102]:

prevent_referred = q2.query('external_referral == "Yes" & service_type == "Preventive (Ongoing)"').student_id.nunique()
prevent_referred

104

In [103]:
q2.query('service_type == "Preventive (Ongoing)"').student_id.nunique()

3569

In [104]:
pcnt_prevent_referred = prevent_referred / q2.query('service_type == "Preventive (Ongoing)"').student_id.nunique()
pcnt_prevent_referred

0.02913981507425049

#5-Q2: The number of unique schools that received support from an SRC in response to a crisis or to provide a preventative service.

In [55]:

#q2.DBN.nunique()

q2_unique_dbns = q2[q2.student_id.notnull()].DBN.nunique()
q2_unique_dbns

174

#5a-Q2: The number of unique schools that received support from an SRC in response to a crisis incident.

In [130]:

q2.query('service_type == "Crisis"').DBN.nunique()

34

#5b-Q2: The number of unique schools that received support from an SRC in response to a preventative service.

In [131]:

q2.query('service_type == "Preventive (Ongoing)"').DBN.nunique()

173

In [132]:

#Unique students served by service format: 'individual_group'
q2.groupby('individual_group').student_id.nunique()

individual_group
1:1 (individual)     815
1:2+ (group)        1831
Name: student_id, dtype: int64

In [133]:
#Number of services provided by service format: 'individual_group'
q2.groupby('individual_group').student_id.count()

individual_group
1:1 (individual)    1996
1:2+ (group)        3325
Name: student_id, dtype: int64

#6-Q2: Number of unique students who have participated in an individual (1:1) mental health session delivered by an SRC in response to a crisis incident. ['individual_group']

In [134]:

crisis_individual = q2.query('individual_group == "1:1 (individual)" & service_type == "Crisis"').student_id.nunique()
crisis_individual

51

#7-Q2: Number of uniques students who have participated in an individual (1:2+) mental health session delivered by an SRC in response to a crisis incident.

In [135]:

crisis_group = q2.query('individual_group == "1:2+ (group)" & service_type == "Crisis"').student_id.nunique()
crisis_group

10

#8-Q2: Number of uniques students who have participated in an individual (1:1) mental health session delivered by an SRC in response to a preventative.

In [136]:

prevent_individual = q2.query('individual_group == "1:1 (individual)" & service_type == "Preventive (Ongoing)"').student_id.nunique()
prevent_individual

802

#9-Q2: Number of uniques students who have participated in an individual (1:2+) mental health session delivered by an SRC in response to a preventative.

In [137]:

prevent_group = q2.query('individual_group == "1:2+ (group)" & service_type == "Preventive (Ongoing)"').student_id.nunique()
prevent_group

1821

In [105]:
# 6 WK ANALYSIS BEGINS HERE**********************
#Need to outline changes and test this data.

#Number of students who have participated in an individual (1:1) mental health session delivered by an SRC up to and including the sixth week post the first preventative service. Need this for both crisis/preventative AND 1:1 / 1:2+

In [106]:
#Find students served more than one time in quarter
#Source: https://stackoverflow.com/questions/14657241/how-do-i-get-a-list-of-all-the-duplicate-items-using-pandas-in-python
#stud_dups = pd.concat(g for _, g in q2.groupby("student_id") if len(g) > 1)

In [107]:
#Find students served more than one time within six weeks 'Date of provided support'
# Source: https://stackoverflow.com/questions/54669337/pandas-dataframe-difference-between-all-dates-for-each-unique-id

stud_dups_sorted = q2.sort_values(['student_id', 'Date of provided support'])

In [108]:
stud_dups_sorted['Datetime'] = pd.to_datetime(stud_dups_sorted['Date of provided support'])                              
g = stud_dups_sorted.groupby('student_id')['Datetime']
print(stud_dups_sorted.groupby('student_id')['Datetime'].apply(lambda g: g.iloc[0] - g.iloc[-1]))

student_id
20999502      0 days
23552843      0 days
200000000   -10 days
200483281     0 days
200674513   -12 days
              ...
273899500     0 days
273946830     0 days
275061588   -28 days
299034277     0 days
299450671   -13 days
Name: Datetime, Length: 3591, dtype: timedelta64[ns]

In [109]:
### df['Time in Status'] = df.groupby('id')['Datetime'].diff(-1)*(-1)
#Time betwen service provides number of days between dates of service for each student

stud_dups_sorted['time_between_service'] = stud_dups_sorted.groupby('student_id')['Datetime'].diff(-1)*(-1)
stud_dups_sorted

,Quarter,Response ID,Time Started,Date Submitted,MONTH,Date Submitted - Simple Date,Days Between Date Submitted and Date Provided,Username:New Login/Password,Password:New Login/Password,"Did you provide support at a school, central office (deployment for staff support ONLY) or REC?",...,What type of staff/family preventive (ongoing) support did you provide?,How many unique school staff members participated in this training?,What type of staff/family crisis response support did you provide?,Student OSIS number of student discussed in case consultation with staff and/or family:,external_referral,Which external health support did you refer this student to?,CASE NOTES,DBN,Datetime,time_between_service
6704,Q2,12387,"Dec 14, 2020 3:24:23 pm","Dec 14, 2020 3:30:27 pm",December,2020-12-14 00:00:00,3,mrosenberg17@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,No,NaN,provided SEL workshop to students,11X299,2020-12-11,NaT
6839,Q2,10448,"Dec 2, 2020 2:29:08 pm","Dec 2, 2020 2:34:22 pm",December,2020-12-02 00:00:00,0,rmorris14@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,No,NaN,Advisement workshop,13K301,2020-12-02,NaT
7740,Q2,11012,"Dec 7, 2020 1:12:22 pm","Dec 7, 2020 1:22:44 pm",December,2020-12-07 00:00:00,0,cknights@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged in individual session with student...,15K462,2020-12-07,8 days
7741,Q2,12630,"Dec 15, 2020 4:03:17 pm","Dec 15, 2020 4:06:02 pm",December,2020-12-15 00:00:00,0,cknights@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged with student in google classroom r...,15K462,2020-12-15,1 days
7301,Q2,13060,"Dec 17, 2020 9:46:44 am","Dec 17, 2020 9:57:41 am",December,2020-12-17 00:00:00,1,cknights@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged with students via google meets for...,15K462,2020-12-16,0 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6121,Q2,13741,"Dec 18, 2020 3:34:50 pm","Dec 18, 2020 3:39:50 pm",December,2020-12-18 00:00:00,0,npeterscamille@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,No,NaN,SRC facilitated a tier 1 workshop with student...,19K364,2020-12-18,NaT
812,Q2,1569,"Oct 7, 2020 3:33:40 pm","Oct 7, 2020 3:41:46 pm",OCTOBER,10/7/2020,0,tyoung19@schools.nyc.gov,NaN,School,...,NaN,NaN,NaN,NaN,No,NaN,SRC conducted the initial check in with schola...,08X530,2020-10-07,NaT
8843,Q2,12126,"Dec 11, 2020 7:53:33 pm","Dec 11, 2020 8:00:50 pm",December,2020-12-11 00:00:00,1,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,No,NaN,Student referred by GC for support around her ...,27Q226,2020-12-10,8 days
8844,Q2,13858,"Dec 18, 2020 6:10:55 pm","Dec 18, 2020 6:22:48 pm",December,2020-12-18 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,No,NaN,Student supported around the challenges she re...,27Q226,2020-12-18,5 days
8845,Q2,14590,"Dec 23, 2020 5:36:26 pm","Dec 23, 2020 5:47:26 pm",December,2020-12-23 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,School,...,NaN,NaN,NaN,NaN,No,NaN,Student shared that she was a different person...,27Q226,2020-12-23,NaT

In [110]:
#Export THRIVE 6-WK data to excel to review and confirm data
stud_dups_sorted.to_excel(r"/Users/holly/Desktop/12292020 Thrive 6 wk Data.xlsx", sheet_name='type',header=True, merge_cells=False)

In [111]:
stud_dups_final = pd.read_excel(r"/Users/holly/Desktop/12292020 Thrive 6 wk Data.xlsx")
stud_dups_final

,Unnamed: 0,Quarter,Response ID,Time Started,Date Submitted,MONTH,Date Submitted - Simple Date,Days Between Date Submitted and Date Provided,Username:New Login/Password,Password:New Login/Password,...,What type of staff/family preventive (ongoing) support did you provide?,How many unique school staff members participated in this training?,What type of staff/family crisis response support did you provide?,Student OSIS number of student discussed in case consultation with staff and/or family:,external_referral,Which external health support did you refer this student to?,CASE NOTES,DBN,Datetime,time_between_service
0,6704,Q2,12387,"Dec 14, 2020 3:24:23 pm","Dec 14, 2020 3:30:27 pm",December,2020-12-14 00:00:00,3,mrosenberg17@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,provided SEL workshop to students,11X299,2020-12-11,NaN
1,6839,Q2,10448,"Dec 2, 2020 2:29:08 pm","Dec 2, 2020 2:34:22 pm",December,2020-12-02 00:00:00,0,rmorris14@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,Advisement workshop,13K301,2020-12-02,NaN
2,7740,Q2,11012,"Dec 7, 2020 1:12:22 pm","Dec 7, 2020 1:22:44 pm",December,2020-12-07 00:00:00,0,cknights@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged in individual session with student...,15K462,2020-12-07,8.0
3,7741,Q2,12630,"Dec 15, 2020 4:03:17 pm","Dec 15, 2020 4:06:02 pm",December,2020-12-15 00:00:00,0,cknights@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged with student in google classroom r...,15K462,2020-12-15,1.0
4,7301,Q2,13060,"Dec 17, 2020 9:46:44 am","Dec 17, 2020 9:57:41 am",December,2020-12-17 00:00:00,1,cknights@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged with students via google meets for...,15K462,2020-12-16,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8485,6121,Q2,13741,"Dec 18, 2020 3:34:50 pm","Dec 18, 2020 3:39:50 pm",December,2020-12-18 00:00:00,0,npeterscamille@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC facilitated a tier 1 workshop with student...,19K364,2020-12-18,NaN
8486,812,Q2,1569,"Oct 7, 2020 3:33:40 pm","Oct 7, 2020 3:41:46 pm",OCTOBER,10/7/2020,0,tyoung19@schools.nyc.gov,NaN,...,NaN,NaN,NaN,NaN,No,NaN,SRC conducted the initial check in with schola...,08X530,2020-10-07,NaN
8487,8843,Q2,12126,"Dec 11, 2020 7:53:33 pm","Dec 11, 2020 8:00:50 pm",December,2020-12-11 00:00:00,1,cpowell18@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,Student referred by GC for support around her ...,27Q226,2020-12-10,8.0
8488,8844,Q2,13858,"Dec 18, 2020 6:10:55 pm","Dec 18, 2020 6:22:48 pm",December,2020-12-18 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,Student supported around the challenges she re...,27Q226,2020-12-18,5.0
8489,8845,Q2,14590,"Dec 23, 2020 5:36:26 pm","Dec 23, 2020 5:47:26 pm",December,2020-12-23 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,Student shared that she was a different person...,27Q226,2020-12-23,NaN

In [112]:
type('time_between_service')

str

In [113]:
#Find duplicate students supported where time_between_service is not null AND is less than 43 days. This will yield all students supported more than once within 6 weeks.
#Source: https://queirozf.com/entries/pandas-query-examples-sql-like-syntax-queries-in-dataframes

time_between_notnull = stud_dups_final.query('time_between_service != "Nan"')
time_between_notnull

,Unnamed: 0,Quarter,Response ID,Time Started,Date Submitted,MONTH,Date Submitted - Simple Date,Days Between Date Submitted and Date Provided,Username:New Login/Password,Password:New Login/Password,...,What type of staff/family preventive (ongoing) support did you provide?,How many unique school staff members participated in this training?,What type of staff/family crisis response support did you provide?,Student OSIS number of student discussed in case consultation with staff and/or family:,external_referral,Which external health support did you refer this student to?,CASE NOTES,DBN,Datetime,time_between_service
2,7740,Q2,11012,"Dec 7, 2020 1:12:22 pm","Dec 7, 2020 1:22:44 pm",December,2020-12-07 00:00:00,0,cknights@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged in individual session with student...,15K462,2020-12-07,8.0
3,7741,Q2,12630,"Dec 15, 2020 4:03:17 pm","Dec 15, 2020 4:06:02 pm",December,2020-12-15 00:00:00,0,cknights@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged with student in google classroom r...,15K462,2020-12-15,1.0
4,7301,Q2,13060,"Dec 17, 2020 9:46:44 am","Dec 17, 2020 9:57:41 am",December,2020-12-17 00:00:00,1,cknights@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged with students via google meets for...,15K462,2020-12-16,0.0
5,7343,Q2,13060,"Dec 17, 2020 9:46:44 am","Dec 17, 2020 9:57:41 am",December,2020-12-17 00:00:00,1,cknights@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged with students via google meets for...,15K462,2020-12-16,1.0
6,7302,Q2,13178,"Dec 17, 2020 12:47:01 pm","Dec 17, 2020 12:48:50 pm",December,2020-12-17 00:00:00,0,nsilverman2@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,Co-facilitated 9th grade health lessons during...,10X434,2020-12-17,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8482,6120,Q2,11156,"Dec 7, 2020 5:00:08 pm","Dec 7, 2020 5:05:24 pm",December,2020-12-07 00:00:00,3,npeterscamille@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC facilitated a tier 1 workshop with student...,19K364,2020-12-04,0.0
8483,6797,Q2,11168,"Dec 7, 2020 5:32:52 pm","Dec 7, 2020 5:37:54 pm",December,2020-12-07 00:00:00,3,npeterscamille@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged virtually with students via google...,19K364,2020-12-04,0.0
8484,7520,Q2,11167,"Dec 7, 2020 5:32:01 pm","Dec 7, 2020 5:36:01 pm",December,2020-12-07 00:00:00,3,npeterscamille@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged virtually with students via google...,19K364,2020-12-04,14.0
8487,8843,Q2,12126,"Dec 11, 2020 7:53:33 pm","Dec 11, 2020 8:00:50 pm",December,2020-12-11 00:00:00,1,cpowell18@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,Student referred by GC for support around her ...,27Q226,2020-12-10,8.0
8488,8844,Q2,13858,"Dec 18, 2020 6:10:55 pm","Dec 18, 2020 6:22:48 pm",December,2020-12-18 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,Student supported around the challenges she re...,27Q226,2020-12-18,5.0

In [114]:
time_between_notnull_less6wks = time_between_notnull.query('time_between_service < 43.0')
time_between_notnull_less6wks

,Unnamed: 0,Quarter,Response ID,Time Started,Date Submitted,MONTH,Date Submitted - Simple Date,Days Between Date Submitted and Date Provided,Username:New Login/Password,Password:New Login/Password,...,What type of staff/family preventive (ongoing) support did you provide?,How many unique school staff members participated in this training?,What type of staff/family crisis response support did you provide?,Student OSIS number of student discussed in case consultation with staff and/or family:,external_referral,Which external health support did you refer this student to?,CASE NOTES,DBN,Datetime,time_between_service
2,7740,Q2,11012,"Dec 7, 2020 1:12:22 pm","Dec 7, 2020 1:22:44 pm",December,2020-12-07 00:00:00,0,cknights@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged in individual session with student...,15K462,2020-12-07,8.0
3,7741,Q2,12630,"Dec 15, 2020 4:03:17 pm","Dec 15, 2020 4:06:02 pm",December,2020-12-15 00:00:00,0,cknights@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged with student in google classroom r...,15K462,2020-12-15,1.0
4,7301,Q2,13060,"Dec 17, 2020 9:46:44 am","Dec 17, 2020 9:57:41 am",December,2020-12-17 00:00:00,1,cknights@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged with students via google meets for...,15K462,2020-12-16,0.0
5,7343,Q2,13060,"Dec 17, 2020 9:46:44 am","Dec 17, 2020 9:57:41 am",December,2020-12-17 00:00:00,1,cknights@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged with students via google meets for...,15K462,2020-12-16,1.0
6,7302,Q2,13178,"Dec 17, 2020 12:47:01 pm","Dec 17, 2020 12:48:50 pm",December,2020-12-17 00:00:00,0,nsilverman2@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,Co-facilitated 9th grade health lessons during...,10X434,2020-12-17,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8482,6120,Q2,11156,"Dec 7, 2020 5:00:08 pm","Dec 7, 2020 5:05:24 pm",December,2020-12-07 00:00:00,3,npeterscamille@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC facilitated a tier 1 workshop with student...,19K364,2020-12-04,0.0
8483,6797,Q2,11168,"Dec 7, 2020 5:32:52 pm","Dec 7, 2020 5:37:54 pm",December,2020-12-07 00:00:00,3,npeterscamille@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged virtually with students via google...,19K364,2020-12-04,0.0
8484,7520,Q2,11167,"Dec 7, 2020 5:32:01 pm","Dec 7, 2020 5:36:01 pm",December,2020-12-07 00:00:00,3,npeterscamille@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,SRC engaged virtually with students via google...,19K364,2020-12-04,14.0
8487,8843,Q2,12126,"Dec 11, 2020 7:53:33 pm","Dec 11, 2020 8:00:50 pm",December,2020-12-11 00:00:00,1,cpowell18@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,Student referred by GC for support around her ...,27Q226,2020-12-10,8.0
8488,8844,Q2,13858,"Dec 18, 2020 6:10:55 pm","Dec 18, 2020 6:22:48 pm",December,2020-12-18 00:00:00,0,cpowell18@schools.nyc.gov,osydsrc2021,...,NaN,NaN,NaN,NaN,No,NaN,Student supported around the challenges she re...,27Q226,2020-12-18,5.0

In [115]:
### NEED TO CHECK THIS DATA TO CONFIRM IT IS WORKING -- SEEMS OFF.

In [116]:
#The number of students who have participated in an individual (1:1) mental health session delivered by an SRC up to and 
#including the sixth week post the first preventative service.
prevent_individual_6wks = time_between_notnull_less6wks.query('individual_group == "1:1 (individual)" & service_type == "Preventive (Ongoing)"').student_id.nunique()
prevent_individual_6wks

597

In [117]:
#The number of students who have participated in an individual (1:2+) mental health session delivered by an SRC up to and 
#including the sixth week post the first preventative service.
prevent_group_6wks = time_between_notnull_less6wks.query('individual_group == "1:2+ (group)" & service_type == "Preventive (Ongoing)"').student_id.nunique()
prevent_group_6wks

1127

In [118]:
#The number of students who have participated in an individual (1:1) mental health session delivered by an SRC up to and 
#including the sixth week post the first crisis service.
crisis_group_6wks = time_between_notnull_less6wks.query('individual_group == "1:2+ (group)" & service_type == "Crisis"').student_id.nunique()
crisis_group_6wks

0

In [119]:
#The number of students who have participated in an individual (1:1) mental health session delivered by an SRC up to and 
#including the sixth week post the first crisis service.
crisis_individual_6wks = time_between_notnull_less6wks.query('individual_group == "1:1 (individual)" & service_type == "Crisis"').student_id.nunique()
crisis_individual_6wks

44